[project]
name = "git_bayesect"
version = "0.1.0"
authors = [{name = "Shantanu Jain"}, {email = "hauntsaninja@gmail.com"}]
description = "Git bisection with Bayesian statistics"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development",
    "Topic :: Utilities",
]
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "scipy",
]

[project.scripts]
git-bayesect = "git_bayesect:main"
git_bayesect = "git_bayesect:main"

[project.urls]
homepage = "https://github.com/hauntsaninja/git_bayesect"
repository = "https://github.com/hauntsaninja/git_bayesect"

[tool.flit.module]
name = "git_bayesect"

[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"
